export default {
    'Meats' : {
        'Turkey' : false,
        'Buffalo Crispy Chicken' : false,
        'Roasted Chicken' : false,
        'Crispy Chicken' : false,
        'Deli Club' : false,
        'Ham' : false,
        'Veggie' : false,
        'Italian' : false,
        'Tuna Salad' : false,
        'Roast Beef' : false,
    },
    'Breads' : {
        'White' : false,
        'Wheat' : false,
        'Italian' : false,
        'Chedder' : false,
        'Garlic' : false,
        'Parmesan' : false,
        'Pretzel' : false,
        'Wrap' : false,
    },
    'Sauces' : {
        'Baja Sauce' : false,
        'BBQ Sauce' : false,
        'Hot Sauce' : false,
        'Salsa' : false,
        'Tomato Sauce' : false,
        'Blue Cheese' : false,
        'Caesar' : false,
        'Italian' : false,
        'Ranch' : false,
        'Oil' : false,
        'Vinegar' : false,
        'Low Fat Mayo' : false,
        'Mayo' : false,
        'Soutern Mayo' : false,
        'Spicy Brown Mustard' : false,
        'Yellow Mustard' : false,
        'Honey Mustard' : false,
    },
    'Toppings' : {
        'Lettuce' : false,
        'Banana Peppers' : false,
        'Black Olives' : false,
        'Carrots' : false,
        'Chopped Romaine Lettuce' : false,
        'Cucumbers' : false,
        'Dill Pickles' : false,
        'Jalepeno Peppers' : false,
        'Mushrooms' : false,
        'Red Peppers' : false,
        'Green Peppers' : false,
        'Roasted Sweet Red Peppers' : false,
        'Shredded Lettuce' : false,
        'Spanish Onions' : false,
        'Onion' : false,
        'Tomato' : false,
    },
    'Cheese' : {
        'American' : false,
        'Mila Chedder' : false,
        'Pepper Jack' : false,
        'Provalone' : false,
        'Shredded Parmesan' : false,
        'Swiss' : false,
    }
}